services:
  app:
    build: .
    container_name: python-project-app
    volumes:
      - ./src:/app/src:ro
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    working_dir: /app
    user: "1000:1000"
    command: ["/opt/venv/bin/python", "src/main.py"]
    
  test:
    image: python-project-app
    container_name: python-project-test
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./pytest.ini:/app/pytest.ini:ro
      - ./.pytest_cache:/app/.pytest_cache
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    working_dir: /app
    user: "1000:1000"
    command: ["/opt/venv/bin/python", "-m", "pytest", "-v"]
    profiles:
      - testing

  dev:
    build: .
    container_name: python-project-dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PATH=/opt/venv/bin:$PATH
      - PYTHONPATH=/app/src
    working_dir: /app
    user: "1000:1000"
    command: /bin/bash
    stdin_open: true
    tty: true
    profiles:
      - development
