name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check if PR is from Dependabot
      id: check-dependabot
      run: |
        if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
          echo "is_dependabot=true" >> $GITHUB_OUTPUT
        else
          echo "is_dependabot=false" >> $GITHUB_OUTPUT
        fi

    - name: Wait for CI checks
      if: steps.check-dependabot.outputs.is_dependabot == 'true'
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: 'test'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30

    - name: Auto-approve Dependabot PRs
      if: steps.check-dependabot.outputs.is_dependabot == 'true'
      run: |
        gh pr review --approve "${{ github.event.pull_request.number }}" --body "Auto-approved by GitHub Actions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-merge Dependabot PRs
      if: steps.check-dependabot.outputs.is_dependabot == 'true'
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}